version: '3'

services:
  db:
    image: postgres
  rabbitmq:
    image: rabbitmq:3.7.7
  web:
    build: .
    volumes:
      - .:/code
    environment:
    - HOST=db
    - NAME=postgres
    - USER=postgres
    - PASSWORD=root
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - rabbitmq
    entrypoint:
    - sh
    - -c
    - |
      sleep 3
      python3 manage.py migrate
      python3 manage.py runserver 0.0.0.0:8000

